### ISSUE TITLE
How to evaluate the performance of MLP on regression-cat-medium-0-OnlineNewsPopularity?

### ISSUE THREAD

**Issue by yangyang2023a** [yandex-research/tabular-dl-tabr#17]
Hello,
From your code, I check the evaluation report.json of MLP on regression-cat-medium-0-OnlineNewsPopularity. And the best epoch metrics is as follows:
 "n_parameters": 495793,
    "prediction_type": null,
    "best_epoch": 26,
    "metrics": {
        "train": {
            "rmse": 0.8142614908186779,
            "mae": 0.5985163409301961,
            "r2": 0.23417308630867428,
            "score": -0.8142614908186779
        },
        "val": {
            "rmse": 0.844946381250874,
            "mae": 0.6250255374955493,
            "r2": 0.15331082859100664,
            "score": -0.844946381250874
        },
        "test": {
            "rmse": 0.8618776869166989,
            "mae": 0.6317802140393205,
            "r2": 0.14868952248971512,
            "score": -0.8618776869166989
        }
    }
Generally, lower values for RMSE and MAE are desirable, and R² closer to 1 indicates better explanatory power of the model. Based on the provided results, the model performs relatively poorly on the validation and test sets, and the R² values suggest a limited explanatory capability.  Is further optimization of the model or consideration of alternative improvement strategies still necessary?  In addition, Tensorboard is provided in the project. How can we analyze this model based on the provided Tensorboard?"
Thanks~

**Comment by Yura52** [comment]
Hello @yangyang2023a 

I think the low R2 is achieved not because of MLP, but because of the dataset. For example, XGBoost performs [better](https://github.com/yandex-research/tabular-dl-tabr/blob/main/exp/xgboost_/why/regression-cat-medium-0-OnlineNewsPopularity/2-evaluation/0/report.json), but in the same "low R2" tier. So it look like the dataset is challenging and/or its features are not very informative.

Our code indeed produces Tensorboard logs, though their are very basic. I am not sure if they are still stored. I think rerunning this one experiment is the easiest way to get similar logs.
