### ISSUE TITLE
add a new dataset

### ISSUE THREAD

**Issue by yz0000314** [yandex-research/tabular-dl-tabr#24]
when i prepared the new dataset in the required format, i tried to apply tabr model to the new dataset. And this is the bug i met when run the command **" python bin/go.py exp/tabr/albert/0-tuning.toml --force  "** 

File "/mnt/user/yezhen/tabular-dl-tabr/lib/data.py", line 122, in <dictcomp>
    part: torch.as_tensor(value).to(device)
TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by Yura52** [comment]
Hi! I am sorry for the slow reply, is the issue still relevant? My first hypothesis is that your dataset (i.e. the numpy arrays) may not follow the recommended data types as described [here](https://github.com/yandex-research/tabular-dl-tabr?tab=readme-ov-file#how-to-add-a-new-dataset).

**Comment by HamidrezaKmK** [comment]
Hi! 
I wanted to second this! I have a table with categorical features, so I store it as `np.str_`. But when it is being read, I face the same exact issue.

**Comment by Yura52** [comment]
@HamidrezaKmK @yz0000314 For datasets with categorical features, for deep learning models, one usually has to set `cat_policy='ordinal'` in a config ([example](https://github.com/yandex-research/tabular-dl-tabr/blob/75105013189c76bc4f247633c2fb856bc948e579/exp/tabr/adult/0-evaluation/0.toml#L12)), exactly in order to convert strings to integer indices. Does this help?

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed!
