### ISSUE TITLE
Default hyperparameters of baseline models

### ISSUE THREAD

**Issue by xumwen** [yandex-research/tabular-dl-tabr#26]
Thank you for the awesome project!

I have a question related to the baseline's hyperparameters.

Do you have any recommendations on the default hyperparameters for MLP, SAINT and FT-Transformer? I think there might be huge performance gap between default hyperparameters and highly-tuned hyperparameters for different datasets. So if one doesn't have enough resources and time for tuning, what might be the modest default hyperparameters for these models?

**Comment by Yura52** [comment]
Hi! FT-Transformer has official default hyperparameters: https://github.com/yandex-research/rtdl-revisiting-models/blob/2542a25b2adbfd0e9d18ce00f75f9f64ad2c26bd/package/rtdl_revisiting_models.py#L752

As far as I remember, SAINT also has official default hyperparameters, but I am not sure.

As for other methods, I don't have any specific configurations in mind, but I have an idea for what you can do. Let's consider MLP. You can collect all tuned hyperparameters for MLP in this repository, using a method described in another our project ([link](https://github.com/yandex-research/rtdl-num-embeddings?tab=readme-ov-file#how-to-explore-metrics-and-hyperparameters)), then summarize them and come up with some default configurations based on what you will see.

Here is my attempt:

```python
import json
from pathlib import Path

import pandas as pd

# Collect all results for tuned MLP for seed=0.
df = pd.json_normalize([
    json.loads(x.read_text())
    for x in Path('exp').glob('mlp/**/0-evaluation/0/report.json')
])
df['config.optimizer.has_weight_decay'] = (
    (df['config.optimizer.weight_decay'] > 0.0).astype(float)
)
df['config.model.backbone.has_dropout'] = (
    (df['config.model.backbone.dropout'] > 0.0).astype(float)
)

# Statistics of the columns starting with "config.optimizer."
df.filter(like='config.optimizer.').describe()

# Statistics of the columns starting with "config.model."
df.filter(like='config.model.').describe()
```

Additional comments:
- Simply using the mean values can be suboptimal, because the mean values can be affected by outliers. I recommend taking everything into account: median, quantiles, mean.
- Overall, using one default configuration will naturally work better for methods that are more robust w.r.t. hyperparameters, and worse for less robust methods. I don't know how it will work for MLP.
- Also, in theory, this approach can result in configurations that are better suited for similar datasets sizes. This is not a bad thing per se, but something to keep in mind.

**Comment by xumwen** [comment]
Got it, thanks for your advise!
